### ISSUE TITLE
relation "auth_user" does not exist

### ISSUE THREAD

**Issue by tcosta84** [macropin/django-registration#48]
Given a newly created django project with the following installed apps:

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'registration',
)

When I run `./manage.py migrate` for the first time I get the following error:

```
Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages, registration
  Apply all migrations: sessions, admin, auth, contenttypes
Synchronizing apps without migrations:
  Creating tables...
    Creating table registration_registrationprofile
    Running deferred SQL...
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/tcosta/Virtualenvs/django_project/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/tcosta/Virtualenvs/django_project/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/tcosta/Virtualenvs/django_project/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/tcosta/Virtualenvs/django_project/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/tcosta/Virtualenvs/django_project/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/Users/tcosta/Virtualenvs/django_project/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 317, in sync_apps
    cursor.execute(statement)
  File "/Users/tcosta/Virtualenvs/django_project/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/tcosta/Virtualenvs/django_project/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/tcosta/Virtualenvs/django_project/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/tcosta/Virtualenvs/django_project/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "auth_user" does not exist```

It seems Django is trying to create the registration tables before the user table.

This erros does not happen if I comment the registration app and run migrate and then uncomment the registration app and run migrate again. However, that's not the right way of doing it, right?

**Comment by drcd** [comment]
I'm having the same issue here. I'm running Django 1.8.1 and Python 3.4.2

**Comment by tcosta84** [comment]
I've had this issue running Django 1.8.1 too (Python 2.7) but I have also tested with 1.7 but still no success.

**Comment by riklaunim** [comment]
Needs https://github.com/macropin/django-registration/pull/25

**Comment by cool-RR** [comment]
This issue affects me too.

**Comment by arthur-s** [comment]
I had the same.
How to handle? first, comment 'registration' in INSTALLED_APPS, then run migration (python manage.py migrate).
After that, you uncomment 'registration', and run migration again.

**Comment by macropin** [comment]
#25 has been merged. Please refer to the release candidate `pip install django-registration-redux==1.2c0`

**Comment by ramaseshan** [comment]
I have been using this with Django 1.6 and south.

SyncDB output :+1: 

(mediaarchival)➜  media_archival git:(develop) ✗ ./manage.py syncdb
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.sessions
 > django.contrib.messages
 > django.contrib.staticfiles
 > django.contrib.sites
 > south
 > mediaarchival

Not synced (use migrations):
 - taggit
 - registration
(use ./manage.py migrate to migrate these)


(mediaarchival)➜  media_archival git:(develop) ✗ ./manage.py migrate
Running migrations for taggit:
- Nothing to migrate.
 - Loading initial data for taggit.
Installed 0 object(s) from 0 fixture(s)
? You have no migrations for the 'registration' app. You might want some.

**Comment by mick-t** [comment]
I having this problem with Django 1.5.12 and django-registration-redux 1.2. I am unable to install the 1.2c0 using the pip command that macropin suggested:

``` 
$ pip install django-registration-redux==1.2c0
Downloading/unpacking django-registration-redux==1.2c0
  Could not find a version that satisfies the requirement django-registration-redux==1.2c0 (from versions: 1.1, 1.2)
```

However this worked:

```
 pip install git+https://github.com/macropin/django-registration.git@v1.2c0
```
