### ISSUE TITLE
AttributeError when using Django 1.8

### ISSUE THREAD

**Issue by sh4r3m4n** [macropin/django-registration#51]
Hi, when I run ./manage.py runserver or ./manage.py shell with django 1.8 and python3 it raises an exception and exits (with py3 and django 1.7 it works perfect):

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/path/to/virtualenv/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/path/to/virtualenv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/path/to/my/project/registration/models.py", line 31, in <module>
    class RegistrationManager(models.Manager):
  File "/path/to/my/project/registration/models.py", line 97, in RegistrationManager
    create_inactive_user = transaction.commit_on_success(create_inactive_user)
AttributeError: 'module' object has no attribute 'commit_on_success'

```

**Comment by AMeng** [comment]
I don't think this is related to `django-registration`. Your traceback points to your own `models.py`. If you look at the Django 1.8 release notes under [Features removed in 1.8](https://docs.djangoproject.com/en/1.8/releases/1.8/#features-removed-in-1-8):

 > the decorators and context managers autocommit, commit_on_success, and commit_manually, defined in django.db.transaction

You need to update your models because `commit_on_success` was removed in Django 1.8. You probably want [django.db.transaction.atomic](https://docs.djangoproject.com/en/1.8/topics/db/transactions/#django.db.transaction.atomic) instead.

**Comment by sh4r3m4n** [comment]
Sorry, i forgot I was using a customized version of the package :D
